// TMDB:s nyckelord finns bara på engelska ("based on novel or book"), och en
// engelsk rubrik i ett svenskt gränssnitt läser som ett fel. Rubriken
// "Tematiskt: …" visas därför bara för nyckelord som har en svensk översättning
// här; övriga teman ger ingen rad. Nycklarna är TMDB:s namn i gemener. Platser
// och rena genrer står inte med: de är inget tema, och genrerna har egna rader.
const SWEDISH_KEYWORDS = new Map<string, string>(Object.entries({
  'based on novel or book': 'bygger på en roman',
  'based on comic': 'bygger på en serietidning',
  'based on true story': 'bygger på en sann historia',
  'based on a true story': 'bygger på en sann historia',
  'based on video game': 'bygger på ett tv-spel',
  'based on manga': 'bygger på en manga',
  'based on play or musical': 'bygger på en pjäs eller musikal',
  'biography': 'biografi',
  'superhero': 'superhjältar',
  'dystopia': 'dystopi',
  'time travel': 'tidsresor',
  'artificial intelligence (a.i.)': 'artificiell intelligens',
  'space': 'rymden',
  'alien': 'utomjordingar',
  'post-apocalyptic future': 'efter katastrofen',
  'zombie': 'zombier',
  'vampire': 'vampyrer',
  'serial killer': 'seriemördare',
  'murder': 'mord',
  'detective': 'detektiver',
  'heist': 'kupper',
  'revenge': 'hämnd',
  'conspiracy': 'konspirationer',
  'politics': 'politik',
  'world war ii': 'andra världskriget',
  'world war i': 'första världskriget',
  'cold war': 'kalla kriget',
  'coming of age': 'uppväxt',
  'high school': 'gymnasiet',
  'friendship': 'vänskap',
  'family': 'familj',
  'dysfunctional family': 'trasiga familjer',
  'female protagonist': 'kvinnlig huvudperson',
  'lgbt': 'hbtqi',
  'mockumentary': 'mockumentär',
  'anthology': 'antologi',
  'miniseries': 'miniserier',
  'sequel': 'uppföljare',
  'remake': 'nyinspelningar',
  'magic': 'magi',
  'dragon': 'drakar',
  'witch': 'häxor',
  'haunted house': 'spökhus',
  'supernatural': 'övernaturligt',
  'small town': 'småstäder',
  'nordic noir': 'nordic noir',
  'police': 'polisen',
  'lawyer': 'advokater',
  'hospital': 'sjukhus',
  'sports': 'sport',
  'music': 'musik',
  'cooking': 'matlagning',
  'survival': 'överlevnad',
  'road trip': 'roadtrips',
}));

export function swedishKeywordLabel(tmdbName: string): string | null {
  return SWEDISH_KEYWORDS.get(tmdbName.trim().toLowerCase()) ?? null;
}
