export interface Country {
  code: string;
  name: string;
}

// Top 10 countries that commonly dominate trending but are culturally distant from Sweden
export const COMMON_FILTER_COUNTRIES = ['IN', 'TR', 'KR', 'JP', 'TH', 'CN', 'RU', 'BR', 'PH', 'ID'];

// All countries with Swedish names, sorted alphabetically by name
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albanien' },
  { code: 'DZ', name: 'Algeriet' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua och Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenien' },
  { code: 'AU', name: 'Australien' },
  { code: 'AZ', name: 'Azerbajdzjan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BE', name: 'Belgien' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnien och Hercegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brasilien' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgarien' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CY', name: 'Cypern' },
  { code: 'DK', name: 'Danmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominikanska republiken' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypten' },
  { code: 'GQ', name: 'Ekvatorialguinea' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'CI', name: 'Elfenbenskusten' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estland' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Etiopien' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'PH', name: 'Filippinerna' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'Frankrike' },
  { code: 'AE', name: 'Förenade Arabemiraten' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgien' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Grekland' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hongkong' },
  { code: 'IN', name: 'Indien' },
  { code: 'ID', name: 'Indonesien' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'Iran' },
  { code: 'IE', name: 'Irland' },
  { code: 'IS', name: 'Island' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italien' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordanien' },
  { code: 'KH', name: 'Kambodja' },
  { code: 'CM', name: 'Kamerun' },
  { code: 'CA', name: 'Kanada' },
  { code: 'CV', name: 'Kap Verde' },
  { code: 'KZ', name: 'Kazakstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'CN', name: 'Kina' },
  { code: 'KG', name: 'Kirgizistan' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KM', name: 'Komorerna' },
  { code: 'CG', name: 'Kongo-Brazzaville' },
  { code: 'CD', name: 'Kongo-Kinshasa' },
  { code: 'HR', name: 'Kroatien' },
  { code: 'CU', name: 'Kuba' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'LA', name: 'Laos' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LV', name: 'Lettland' },
  { code: 'LB', name: 'Libanon' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libyen' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Litauen' },
  { code: 'LU', name: 'Luxemburg' },
  { code: 'MG', name: 'Madagaskar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldiverna' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MA', name: 'Marocko' },
  { code: 'MH', name: 'Marshallöarna' },
  { code: 'MR', name: 'Mauretanien' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexiko' },
  { code: 'FM', name: 'Mikronesien' },
  { code: 'MD', name: 'Moldavien' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongoliet' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MZ', name: 'Moçambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NL', name: 'Nederländerna' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'KP', name: 'Nordkorea' },
  { code: 'MK', name: 'Nordmakedonien' },
  { code: 'NO', name: 'Norge' },
  { code: 'NZ', name: 'Nya Zeeland' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestina' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua Nya Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PL', name: 'Polen' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Rumänien' },
  { code: 'RU', name: 'Ryssland' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts och Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent och Grenadinerna' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'São Tomé och Príncipe' },
  { code: 'SA', name: 'Saudiarabien' },
  { code: 'CH', name: 'Schweiz' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbien' },
  { code: 'SC', name: 'Seychellerna' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakien' },
  { code: 'SI', name: 'Slovenien' },
  { code: 'SB', name: 'Salomonöarna' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ES', name: 'Spanien' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'GB', name: 'Storbritannien' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Surinam' },
  { code: 'SE', name: 'Sverige' },
  { code: 'SY', name: 'Syrien' },
  { code: 'ZA', name: 'Sydafrika' },
  { code: 'KR', name: 'Sydkorea' },
  { code: 'SS', name: 'Sydsudan' },
  { code: 'TJ', name: 'Tadzjikistan' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TD', name: 'Tchad' },
  { code: 'TH', name: 'Thailand' },
  { code: 'CZ', name: 'Tjeckien' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad och Tobago' },
  { code: 'TN', name: 'Tunisien' },
  { code: 'TR', name: 'Turkiet' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'DE', name: 'Tyskland' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraina' },
  { code: 'HU', name: 'Ungern' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'US', name: 'USA' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VA', name: 'Vatikanstaten' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Jemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
  { code: 'AT', name: 'Österrike' },
  { code: 'TL', name: 'Östtimor' },
];

const COUNTRY_MAP = new Map(COUNTRIES.map(c => [c.code, c]));

export function getCountryName(code: string): string {
  return COUNTRY_MAP.get(code)?.name ?? code;
}
